export const tokyoNightTheme = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "", background: "1a1b26", foreground: "c0caf5" },
    { token: "comment", foreground: "565f89", fontStyle: "italic" },
    { token: "keyword", foreground: "bb9af7" },
    { token: "storage", foreground: "bb9af7" },
    { token: "variable", foreground: "c0caf5" },
    { token: "variable.parameter", foreground: "e0af68" },
    { token: "constant", foreground: "ff9e64" },
    { token: "constant.language", foreground: "ff9e64" },
    { token: "constant.numeric", foreground: "ff9e64" },
    { token: "string", foreground: "9ece6a" },
    { token: "string.regexp", foreground: "b4f9f8" },
    { token: "entity.name.function", foreground: "7aa2f7" },
    { token: "entity.name.type", foreground: "2ac3de" },
    { token: "entity.name.class", foreground: "2ac3de" },
    { token: "entity.name.tag", foreground: "f7768e" },
    { token: "entity.other.attribute-name", foreground: "7dcfff" },
    { token: "support.function", foreground: "7aa2f7" },
    { token: "support.constant", foreground: "7dcfff" },
    { token: "support.type", foreground: "2ac3de" },
    { token: "support.class", foreground: "2ac3de" },
    { token: "punctuation.definition.comment", foreground: "565f89" },
    { token: "punctuation.definition.string", foreground: "9ece6a" },
    { token: "punctuation", foreground: "89ddff" },
    { token: "meta.brace", foreground: "89ddff" },
    { token: "meta.delimiter.period", foreground: "89ddff" },
    { token: "keyword.operator", foreground: "89ddff" },
    { token: "keyword.control", foreground: "bb9af7" },
    { token: "markup.bold", foreground: "c0caf5", fontStyle: "bold" },
    { token: "markup.italic", foreground: "bb9af7", fontStyle: "italic" },
    { token: "markup.underline.link", foreground: "73daca", fontStyle: "underline" },
    { token: "markup.heading", foreground: "7dcfff", fontStyle: "bold" },
    { token: "invalid", foreground: "ffffff", background: "f7768e" },
    { token: "invalid.deprecated", foreground: "ffffff", background: "ff9e64" }
  ],
  colors: {
    "editor.foreground": "#c0caf5",
    "editor.background": "#0b0d18",                
    "editor.selectionBackground": "#2b3a66",       
    "editor.lineHighlightBackground": "#10121e",   
    "editorCursor.foreground": "#c0caf5",
    "editorWhitespace.foreground": "#2a2f45",
    "editorIndentGuide.background": "#2a2f45",
    "editorIndentGuide.activeBackground": "#4a4f78",
    "editorLineNumber.foreground": "#2a2f45",
    "editorLineNumber.activeForeground": "#7aa2f7",
    "editor.selectionHighlightBorder": "#1d2740",

    "scrollbar.shadow": "#00000040",               
    "scrollbarSlider.background": "#2a2f45b3",     
    "scrollbarSlider.hoverBackground": "#3b4261cc",
    "scrollbarSlider.activeBackground": "#565f89cc"
  }

}
